Repository Khushii-Arora/SmallWorkingProjects_Hacktoberfest22, pull requests merged in 2022-10, with the labels that each got.

#1 Added a web dev project.
  Web Dev Projects/Stone Paper Scissor Game/README.md
  Web Dev Projects/Stone Paper Scissor Game/app.js
  Web Dev Projects/Stone Paper Scissor Game/assets/paper.png
  Web Dev Projects/Stone Paper Scissor Game/assets/rock.png
  Web Dev Projects/Stone Paper Scissor Game/assets/scissors.png
  Web Dev Projects/Stone Paper Scissor Game/index.html
  Web Dev Projects/Stone Paper Scissor Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#2 Added a python project!
  Python Project/password_generator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#3 Stone-Paper-Scissor Game in Java
  JAVA Project/StonePaperScissor.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#4 Create Plagiarism_Checker.py
  Python Project/Plagiarism_Checker.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#5 Temprature Converter in java
  JAVA Project/Temprature Converter
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#7 Added guessNumber.py
  Python Project/guessNumber.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#8 Added Modal Window Project.
  Web Dev Projects/Modal Window/index.html
  Web Dev Projects/Modal Window/script.js
  Web Dev Projects/Modal Window/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#10 Added Footer Animation under Web Dev Projects Directory
  Web Dev Projects/Footer Animation/Designs/footer_animation.mp4
  Web Dev Projects/Footer Animation/Designs/wave.png
  Web Dev Projects/Footer Animation/README.md
  Web Dev Projects/Footer Animation/index.html
  Web Dev Projects/Footer Animation/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#11 Student grade system
  Python Project/Student Grading System.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#12 Added nft Preview Card Component under Web Dev Projects directory
  Web Dev Projects/nft Preview Card Component/README.md
  Web Dev Projects/nft Preview Card Component/design/active-states.jpg
  Web Dev Projects/nft Preview Card Component/design/desktop-design.jpg
  Web Dev Projects/nft Preview Card Component/design/desktop-preview.jpg
  Web Dev Projects/nft Preview Card Component/design/mobile-design.jpg
  Web Dev Projects/nft Preview Card Component/images/favicon-32x32.png
  Web Dev Projects/nft Preview Card Component/images/icon-clock.svg
  Web Dev Projects/nft Preview Card Component/images/icon-ethereum.svg
  Web Dev Projects/nft Preview Card Component/images/icon-view.svg
  Web Dev Projects/nft Preview Card Component/images/image-avatar.png
  Web Dev Projects/nft Preview Card Component/images/image-equilibrium.jpg
  Web Dev Projects/nft Preview Card Component/index.html
  Web Dev Projects/nft Preview Card Component/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#13 A small car game
  Web Dev Projects/CarGame/bg.jpg
  Web Dev Projects/CarGame/blue.png
  Web Dev Projects/CarGame/index.html
  Web Dev Projects/CarGame/jumpsound.mp3
  Web Dev Projects/CarGame/main.js
  Web Dev Projects/CarGame/race.png
  Web Dev Projects/CarGame/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#14 Rock paper scissors game
  JAVA Project/Rock Paper ScssiorGame.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#15 Added a TeamPage
  Web Dev Projects/teampage/download.png
  Web Dev Projects/teampage/lady.jpg
  Web Dev Projects/teampage/man.jpg
  Web Dev Projects/teampage/team.css
  Web Dev Projects/teampage/team.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#16 Created Snake Game
  Python Project/Snake_game.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#21 Farmer Website & Snake Game
  Final Mini Project/2.jpg
  Final Mini Project/DFD Chart.png
  Final Mini Project/Guava.jpg
  Final Mini Project/Home.css
  Final Mini Project/Home.html
  Final Mini Project/Rice.jpg
  Final Mini Project/Service.css
  Final Mini Project/Services.html
  Final Mini Project/aboutus.css
  Final Mini Project/aboutus.html
  Final Mini Project/back.jpg
  Final Mini Project/banana.jpg
  Final Mini Project/help.jpg
  Final Mini Project/image.jpg
  Final Mini Project/image1.jfif
  Final Mini Project/image2.jpg
  Final Mini Project/land.jpg
  Final Mini Project/login.css
  Final Mini Project/login.html
  Final Mini Project/login.png
  Final Mini Project/mail.png
  Final Mini Project/mango.jpg
  Final Mini Project/pineapple.jpg
  Final Mini Project/signup.css
  Final Mini Project/signup.html
  Final Mini Project/trust.jpg
  Final Mini Project/wheat.jpg
  Snake Game/1.html
  Snake Game/1.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#23 Flappy Bird Game
  Flappy Bird/flappy.css
  Flappy Bird/flappy.html
  Flappy Bird/flappy.js
  Flappy Bird/images/bg.png
  Flappy Bird/images/bird.png
  Flappy Bird/images/fg.png
  Flappy Bird/images/pipeNorth.png
  Flappy Bird/images/pipeSouth.png
  Flappy Bird/sounds/fly.mp3
  Flappy Bird/sounds/score.mp3
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#24 CalculatorWithJS
  Calculator-with-JS/custom.css
  Calculator-with-JS/index.html
  Calculator-with-JS/simplecalculator.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#25 My new branch
  Python Project/pencil_sketching.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#27 Dino Run Game
  Dino Run Game/.idea/.gitignore
  Dino Run Game/.idea/Dino Run Game.iml
  Dino Run Game/.idea/inspectionProfiles/profiles_settings.xml
  Dino Run Game/.idea/misc.xml
  Dino Run Game/.idea/modules.xml
  Dino Run Game/READ ME FIRST !!!!.txt
  Dino Run Game/Screenshot Dino.PNG
  Dino Run Game/main.py
  Dino Run Game/sprites/cacti-big.png
  Dino Run Game/sprites/cacti-small.png
  Dino Run Game/sprites/checkPoint.wav
  Dino Run Game/sprites/cloud.png
  Dino Run Game/sprites/die.wav
  Dino Run Game/sprites/dino.png
  Dino Run Game/sprites/dino_ducking.png
  Dino Run Game/sprites/game_over.png
  Dino Run Game/sprites/ground.png
  Dino Run Game/sprites/jump.wav
  Dino Run Game/sprites/logo.png
  Dino Run Game/sprites/numbers.png
  Dino Run Game/sprites/offline-sprite-2x-black.png
  Dino Run Game/sprites/ptera.png
  Dino Run Game/sprites/replay_button.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#28 JavaScript Tip calculator
  Tip-Calculator-with-js/index.html
  Tip-Calculator-with-js/script.js
  Tip-Calculator-with-js/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#29 Adds countdown timer
  Web Dev Projects/countdown-timer/README.md
  Web Dev Projects/countdown-timer/assets/tones/Alarm05.wav
  Web Dev Projects/countdown-timer/index.html
  Web Dev Projects/countdown-timer/scripts/main.js
  Web Dev Projects/countdown-timer/styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#31 Added a counter for convenience
  Web Dev Projects/Counter/counter.css
  Web Dev Projects/Counter/counter.html
  Web Dev Projects/Counter/counter.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#34 Added Order Summary Component under Web Dev Projects directory
  Web Dev Projects/Order Summary Component/README.md
  Web Dev Projects/Order Summary Component/design/active-states.jpg
  Web Dev Projects/Order Summary Component/design/desktop-design.jpg
  Web Dev Projects/Order Summary Component/design/desktop-preview.jpg
  Web Dev Projects/Order Summary Component/design/mobile-design.jpg
  Web Dev Projects/Order Summary Component/images/favicon-32x32.png
  Web Dev Projects/Order Summary Component/images/icon-music.svg
  Web Dev Projects/Order Summary Component/images/illustration-hero.svg
  Web Dev Projects/Order Summary Component/images/pattern-background-desktop.svg
  Web Dev Projects/Order Summary Component/images/pattern-background-mobile.svg
  Web Dev Projects/Order Summary Component/index.html
  Web Dev Projects/Order Summary Component/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#36 Added Resume Template
  Web Dev Projects/Resume-Template/.gitignore
  Web Dev Projects/Resume-Template/Chrome_sample.jpg
  Web Dev Projects/Resume-Template/Chrome_sample.pdf
  Web Dev Projects/Resume-Template/LICENSE
  Web Dev Projects/Resume-Template/README.md
  Web Dev Projects/Resume-Template/bold+italic.gif
  Web Dev Projects/Resume-Template/editing_full.gif
  Web Dev Projects/Resume-Template/enter.gif
  Web Dev Projects/Resume-Template/index.html
  Web Dev Projects/Resume-Template/index.js
  Web Dev Projects/Resume-Template/paper.css
  Web Dev Projects/Resume-Template/print.css
  Web Dev Projects/Resume-Template/screen.css
  Web Dev Projects/Resume-Template/shift+enter.gif
  Web Dev Projects/Resume-Template/styles.css
  Web Dev Projects/Resume-Template/typography.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#38 added files for todo list application
  todobynisha/Procfile
  todobynisha/index.html
  todobynisha/index.js
  todobynisha/package-lock.json
  todobynisha/package.json
  todobynisha/public/Photos/favicon.ico
  todobynisha/public/stylesheets/styles.css
  todobynisha/public/stylesheets/styles2.css
  todobynisha/views/footer.ejs
  todobynisha/views/header.ejs
  todobynisha/views/index.ejs
  todobynisha/views/index2.ejs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#42 Create tictactoe.py
  Python Project/tictactoe.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#46 Create UrlShortener
  JAVA Project/UrlShortener.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#48 Added dino game to Python Project folder
  Python Project/Dino Run Game/.idea/.gitignore
  Python Project/Dino Run Game/.idea/Dino Run Game.iml
  Python Project/Dino Run Game/.idea/inspectionProfiles/profiles_settings.xml
  Python Project/Dino Run Game/.idea/misc.xml
  Python Project/Dino Run Game/.idea/modules.xml
  Python Project/Dino Run Game/READ ME FIRST !!!!.txt
  Python Project/Dino Run Game/Screenshot Dino.PNG
  Python Project/Dino Run Game/main.py
  Python Project/Dino Run Game/sprites/cacti-big.png
  Python Project/Dino Run Game/sprites/cacti-small.png
  Python Project/Dino Run Game/sprites/checkPoint.wav
  Python Project/Dino Run Game/sprites/cloud.png
  Python Project/Dino Run Game/sprites/die.wav
  Python Project/Dino Run Game/sprites/dino.png
  Python Project/Dino Run Game/sprites/dino_ducking.png
  Python Project/Dino Run Game/sprites/game_over.png
  Python Project/Dino Run Game/sprites/ground.png
  Python Project/Dino Run Game/sprites/jump.wav
  Python Project/Dino Run Game/sprites/logo.png
  Python Project/Dino Run Game/sprites/numbers.png
  Python Project/Dino Run Game/sprites/offline-sprite-2x-black.png
  Python Project/Dino Run Game/sprites/ptera.png
  Python Project/Dino Run Game/sprites/replay_button.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#50 Create RockPaperScissor_Game.py
  Python Project/RockPaperScissor_Game.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#53 Created Tic-Tac-Toe Game
  JAVA Project/Tic-Tac-Toe Game.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#54 Created Scientific GUI Calculator
  Python Project/Scientific GUI Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#58 Nft Generator
  BlockChain Project/NftMinter.sol
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#60 CountDown Timer
  JS Project/timer/index.html
  JS Project/timer/index.js
  JS Project/timer/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#61 add blockchain-digi-certificate system
  BlockChain Project/blockchain-certificate-master/README.md
  BlockChain Project/blockchain-certificate-master/package-lock.json
  BlockChain Project/blockchain-certificate-master/package.json
  BlockChain Project/blockchain-certificate-master/public/favicon.ico
  BlockChain Project/blockchain-certificate-master/public/index.html
  BlockChain Project/blockchain-certificate-master/public/manifest.json
  BlockChain Project/blockchain-certificate-master/public/robots.txt
  BlockChain Project/blockchain-certificate-master/src/App.css
  BlockChain Project/blockchain-certificate-master/src/App.js
  BlockChain Project/blockchain-certificate-master/src/assets/Next steps-pana.png
  BlockChain Project/blockchain-certificate-master/src/assets/Next steps-pana.svg
  BlockChain Project/blockchain-certificate-master/src/components/Button.jsx
  BlockChain Project/blockchain-certificate-master/src/components/Navbar.jsx
  BlockChain Project/blockchain-certificate-master/src/components/Success.jsx
  BlockChain Project/blockchain-certificate-master/src/config.js
  BlockChain Project/blockchain-certificate-master/src/contracts/CertificateContract.json
  BlockChain Project/blockchain-certificate-master/src/index.css
  BlockChain Project/blockchain-certificate-master/src/index.js
  BlockChain Project/blockchain-certificate-master/src/pages/ConnectWallet.jsx
  BlockChain Project/blockchain-certificate-master/src/pages/Home.jsx
  BlockChain Project/blockchain-certificate-master/src/pages/Upload.jsx
  BlockChain Project/blockchain-certificate-master/src/pages/Verify.jsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#62 added a project split landing page- JS
  JS Project/Split Landing Page/image1.jfif
  JS Project/Split Landing Page/image2.jfif
  JS Project/Split Landing Page/index.html
  JS Project/Split Landing Page/script.js
  JS Project/Split Landing Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#63 Hacktoberfest 2022
  Phone Number Location Tracker.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#67 added a web development proj
  Web Dev Projects/website 1/index.html
  Web Dev Projects/website 1/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#68 added candy crush clone react
  Web Dev Projects/candy-crush-clone-react/README.md
  Web Dev Projects/candy-crush-clone-react/package-lock.json
  Web Dev Projects/candy-crush-clone-react/package.json
  Web Dev Projects/candy-crush-clone-react/postcss.config.js
  Web Dev Projects/candy-crush-clone-react/public/favicon.ico
  Web Dev Projects/candy-crush-clone-react/public/index.html
  Web Dev Projects/candy-crush-clone-react/public/logo192.png
  Web Dev Projects/candy-crush-clone-react/public/logo512.png
  Web Dev Projects/candy-crush-clone-react/public/manifest.json
  Web Dev Projects/candy-crush-clone-react/public/robots.txt
  Web Dev Projects/candy-crush-clone-react/src/App.tsx
  Web Dev Projects/candy-crush-clone-react/src/assets/background.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candyFive.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candyFour.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candyOne.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candySeven.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candySix.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candyThree.png
  Web Dev Projects/candy-crush-clone-react/src/assets/candyTwo.png
  Web Dev Projects/candy-crush-clone-react/src/components/Board.tsx
  Web Dev Projects/candy-crush-clone-react/src/components/Tile.tsx
  Web Dev Projects/candy-crush-clone-react/src/index.css
  Web Dev Projects/candy-crush-clone-react/src/index.tsx
  Web Dev Projects/candy-crush-clone-react/src/react-app-env.d.ts
  Web Dev Projects/candy-crush-clone-react/src/store/hooks.ts
  Web Dev Projects/candy-crush-clone-react/src/store/index.ts
  Web Dev Projects/candy-crush-clone-react/src/store/reducers/dragEnd.ts
  Web Dev Projects/candy-crush-clone-react/src/store/reducers/moveBelow.ts
  Web Dev Projects/candy-crush-clone-react/src/utils/candyData.ts
  Web Dev Projects/candy-crush-clone-react/src/utils/createBoard.ts
  Web Dev Projects/candy-crush-clone-react/src/utils/formulas.ts
  Web Dev Projects/candy-crush-clone-react/src/utils/moveCheckLogic.ts
  Web Dev Projects/candy-crush-clone-react/tailwind.config.js
  Web Dev Projects/candy-crush-clone-react/tsconfig.json
  Web Dev Projects/candy-crush-clone-react/yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#69 cafe landing page
  Web Dev Projects/Cafe Landing Page/images/1111.PNG
  Web Dev Projects/Cafe Landing Page/images/222222.PNG
  Web Dev Projects/Cafe Landing Page/images/cake1.PNG
  Web Dev Projects/Cafe Landing Page/images/cake2.PNG
  Web Dev Projects/Cafe Landing Page/images/deck1.PNG
  Web Dev Projects/Cafe Landing Page/images/deck2.PNG
  Web Dev Projects/Cafe Landing Page/images/deck3.PNG
  Web Dev Projects/Cafe Landing Page/images/deck4.PNG
  Web Dev Projects/Cafe Landing Page/images/final1.PNG
  Web Dev Projects/Cafe Landing Page/images/final2.PNG
  Web Dev Projects/Cafe Landing Page/images/final3.PNG
  Web Dev Projects/Cafe Landing Page/images/final4.PNG
  Web Dev Projects/Cafe Landing Page/images/final5.PNG
  Web Dev Projects/Cafe Landing Page/images/final6.PNG
  Web Dev Projects/Cafe Landing Page/images/first.PNG
  Web Dev Projects/Cafe Landing Page/images/fuh.jfif
  Web Dev Projects/Cafe Landing Page/images/logo.PNG
  Web Dev Projects/Cafe Landing Page/images/logo1.PNG
  Web Dev Projects/Cafe Landing Page/images/maining.jfif
  Web Dev Projects/Cafe Landing Page/images/one.jfif
  Web Dev Projects/Cafe Landing Page/images/soon.PNG
  Web Dev Projects/Cafe Landing Page/images/yoo.PNG
  Web Dev Projects/Cafe Landing Page/index.html
  Web Dev Projects/Cafe Landing Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#71 Parking management system project add in C++
  CPP Project/Parking Management System.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#72 ADD this mini_project A car_rental_system written c++.
  CPP Project/Car_Rental_system/README.md
  CPP Project/Car_Rental_system/car_rental_system.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#73 Added Dice game
  Web Dev Projects/Dice game/dice.css
  Web Dev Projects/Dice game/dice.html
  Web Dev Projects/Dice game/dice.js
  Web Dev Projects/Dice game/dice1.png
  Web Dev Projects/Dice game/dice2.png
  Web Dev Projects/Dice game/dice3.png
  Web Dev Projects/Dice game/dice4.png
  Web Dev Projects/Dice game/dice5.png
  Web Dev Projects/Dice game/dice6.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#74 added Pig Game Project
  JS Project/Pig Game/.prettierrc
  JS Project/Pig Game/PigGameReadme.md
  JS Project/Pig Game/dice-1.png
  JS Project/Pig Game/dice-2.png
  JS Project/Pig Game/dice-3.png
  JS Project/Pig Game/dice-4.png
  JS Project/Pig Game/dice-5.png
  JS Project/Pig Game/dice-6.png
  JS Project/Pig Game/index.html
  JS Project/Pig Game/pig-game-flowchart.png
  JS Project/Pig Game/script.js
  JS Project/Pig Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#76 Create ping_pong_game.py
  Python Project/ping_pong_game.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#78 Added Automatic Birthday Wisher Project
  Python Project/Automatic Birthday Wisher/data.xlsx
  Python Project/Automatic Birthday Wisher/main.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#79 JSON Formatter Application
  JS Project/Json Formatter/README.md
  JS Project/Json Formatter/index.html
  JS Project/Json Formatter/script.js
  JS Project/Json Formatter/style.csss
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#80 otp verification
  JS Project/otpverification/index.html
  JS Project/otpverification/script.js
  JS Project/otpverification/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#81 added ML project
  Machine Learning Projects/Diabetes Prediction Using ML/kaggle_diabetes.csv
  Machine Learning Projects/Diabetes Prediction Using ML/mini_project.ipynb
  Machine Learning Projects/Diabetes Prediction Using ML/readme.md
  Machine Learning Projects/Diabetes Prediction Using ML/result.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#82 New ML Project Added : Harry Potter Invisible Cloak
  Machine Learning Projects/Harry_Potter_invisible_cloak/Invisible_cloak.py
  Machine Learning Projects/Harry_Potter_invisible_cloak/rough
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#83 added flip-loading button
  Web Dev Projects/Modal Window/index.html
  Web Dev Projects/Modal Window/style.css
  Web Dev Projects/Order Summary Component/flip.js
  Web Dev Projects/Order Summary Component/index.html
  Web Dev Projects/Order Summary Component/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#110 Fake News Detection Using ML
  Machine Learning Projects\Fake News Detection Using ML/FakeNews_Detection.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#102 Added bounce ball animation.
  CPP Project/Bouncing-Ball-Animation/README.md
  CPP Project/Bouncing-Ball-Animation/src/Screenshot1.png
  CPP Project/Bouncing-Ball-Animation/src/Screenshot2.png
  CPP Project/Bouncing-Ball-Animation/src/ball.cpp
  CPP Project/Bouncing-Ball-Animation/src/ball.h
  CPP Project/Bouncing-Ball-Animation/src/bg.bmp
  CPP Project/Bouncing-Ball-Animation/src/eventHandling.cpp
  CPP Project/Bouncing-Ball-Animation/src/eventHandling.h
  CPP Project/Bouncing-Ball-Animation/src/gui.cpp
  CPP Project/Bouncing-Ball-Animation/src/gui.h
  CPP Project/Bouncing-Ball-Animation/src/imageloader.cpp
  CPP Project/Bouncing-Ball-Animation/src/imageloader.h
  CPP Project/Bouncing-Ball-Animation/src/main.cpp
  CPP Project/Bouncing-Ball-Animation/src/makefile
  CPP Project/Bouncing-Ball-Animation/src/tinyfiledialogs.c
  CPP Project/Bouncing-Ball-Animation/src/tinyfiledialogs.h
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#106 Jarvis {AI assistance}
  jarvis.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#109 Jumbled Words Game in Python
  Python Project/jumbledWordsGane.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#111 Simple Digital Clock with GUI
  Python Project/simpleDigital_clock.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#117 Update dice.html
  Web Dev Projects/Dice game/dice.html
Labels: hacktoberfest-accepted
